name: Auto Update

on:
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update Index
        run: |
          python ./auto/run.py

      - name: Commit
        run: |
          git config --global user.email fengyiyi@yeah.net
          git config --global user.name fengyiyi
          git add .
          git commit -m "Update Index" -a

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ONESS }}
